

import { createContext } from 'react';
import type { IAppContext } from '../types';
import { Screens } from '../constants';

export const initialAppContext: IAppContext = {
  role: 'unauthenticated',
  user: null,
  users: [],
  screen: Screens.WELCOME,
  activePatientScreen: Screens.PATIENT_HOME,
  language: 'English',
  t: (key: string) => key, // Placeholder translation function
  isGuestUpgrading: false,
  setIsGuestUpgrading: () => console.warn('setIsGuestUpgrading not yet initialized'),
  login: (_email, _password) => Promise.reject('login function not yet initialized'),
  register: (_details) => Promise.reject('register function not yet initialized'),
  loginAsGuest: () => console.warn('loginAsGuest function not yet initialized'),
  logout: () => console.warn('logout function not yet initialized'),
  promptGuestExit: () => console.warn('promptGuestExit function not yet initialized'),
  navigateTo: (_screen) => console.warn('navigateTo function not yet initialized'),
  setLanguage: (_language) => console.warn('setLanguage function not yet initialized'),
  startSymptomCheck: (_initialSymptom) => console.warn('startSymptomCheck function not yet initialized'),
  symptom: null,
  updateGuestDetails: (_details) => { 
    console.warn('updateGuestDetails function not yet initialized');
    return { id: 'guest', name: 'Guest', email: '', role: 'guest', status: 'active', address: { barangay: '', purok: '', streetAddress: ''} };
  },
  updateUserProfile: (_updatedUser) => console.warn('updateUserProfile function not yet initialized'),
  addProfessionalUser: (_user) => console.warn('addProfessionalUser function not yet initialized'),
  updateProfessionalProfile: (_userId, _userUpdates, _profileUpdates) => Promise.reject('updateProfessionalProfile not yet initialized'),
  addResidentRecord: (_details) => console.warn('addResidentRecord function not yet initialized'),
  deleteResidentRecord: (_recordId) => console.warn('deleteResidentRecord function not yet initialized'),
  updateResidentRecord: (_recordId, _details) => console.warn('updateResidentRecord function not yet initialized'),
  residentRecords: [],
  updateUserStatus: (_userId, _status) => console.warn('updateUserStatus function not yet initialized'),
  deleteUser: (_userId) => console.warn('deleteUser function not yet initialized'),
  addReportToUser: (_userId, _report) => console.warn('addReportToUser function not yet initialized'),
  activeConsultation: null,
  setActiveConsultation: (_consultation) => console.warn('setActiveConsultation function not yet initialized'),
  consultations: [],
  addConsultation: (_consultation) => { console.warn('addConsultation function not yet initialized'); return Promise.resolve(); },
  updateConsultationStatus: (_consultationId, _status, _doctorId) => console.warn('updateConsultationStatus function not yet initialized'),
  activePrescription: null,
  setActivePrescription: (_prescription) => console.warn('setActivePrescription function not yet initialized'),
  prescriptions: [],
  medicines: [],
  addPrescription: (_prescription) => console.warn('addPrescription function not yet initialized'),
  updatePrescription: (_prescriptionId, _details) => console.warn('updatePrescription function not yet initialized'),
  activePatientForManagement: null,
  setActivePatientForManagement: (_user) => console.warn('setActivePatientForManagement not yet initialized'),
  forumPosts: [],
  addForumPost: (_content) => console.warn('addForumPost function not yet initialized'),
  activePrivateChatRecipient: null,
  setActivePrivateChatRecipient: (_user) => console.warn('setActivePrivateChatRecipient not yet initialized'),
  privateChats: {},
  sendPrivateMessage: (_recipientId, _content) => console.warn('sendPrivateMessage function not yet initialized'),
  activeDoctorChatRecipient: null,
  setActiveDoctorChatRecipient: (_doctor) => console.warn('setActiveDoctorChatRecipient not yet initialized'),
  patientDoctorChats: {},
  sendPatientDoctorMessage: (_doctorId, _content) => console.warn('sendPatientDoctorMessage function not yet initialized'),
  sendDoctorPatientMessage: (_patientId, _content) => console.warn('sendDoctorPatientMessage function not yet initialized'),
  markDoctorChatAsRead: (_conversationId) => console.warn('markDoctorChatAsRead function not yet initialized'),
  doctorProfiles: [],
  updateDoctorAvailability: (_doctorId, _availability) => console.warn('updateDoctorAvailability function not yet initialized'),
  upgradeUserSubscription: (_userId, _plan) => console.warn('upgradeUserSubscription function not yet initialized'),
  grantPremiumSubscription: (_userId) => console.warn('grantPremiumSubscription function not yet initialized'),
  rhuStats: null,
  bhwStats: null,
  pharmacyStats: null,
  bhwNotifications: [],
  approveIdVerification: (_notificationId) => console.warn('approveIdVerification not yet initialized'),
  rejectIdVerification: (_notificationId, _reason) => console.warn('rejectIdVerification not yet initialized'),
  patientNotifications: [],
  markPatientNotificationAsRead: (_notificationId) => console.warn('markPatientNotificationAsRead not yet initialized'),
  updateValidId: (_file) => Promise.reject('updateValidId not yet initialized'),
  pendingConsultationForGuest: null,
  setPendingConsultationForGuest: (_data) => console.warn('setPendingConsultationForGuest not yet initialized'),
  validateAndRemitPrescription: (_prescriptionId) => Promise.reject('validateAndRemitPrescription not yet initialized'),
};

export const AppContext = createContext<IAppContext>(initialAppContext);